app:
  name: "Solo-Mission-Api-Service"
  host: "0.0.0.0:18080"
  env: "debug" # should be debug, release, test


  isSave: false
  format: "console"
  level: "info"
  path: "./logs/log"

redis:
  enableCluster: false
  addressList: ["127.0.0.1:63790"]
  password: ""
  db: 0
  prefix: ""

mysql:
  dsn: "root:123456@tcp(127.0.0.1:53306)/fido?charset=utf8&parseTime=True&loc=Local"
  maxIdleConns: 3
  maxOpenConns: 10
  slowThreshold: 0s
  connMaxLifetime: 30m
  enableLog: false

middleware:
  enableCircuitBreaker: false
  enableRateLimit: false
  enableMetrics: false
  enableTrace: false
