app:
  name: "Solo-Mission-Api-Service"
  host: "127.0.0.1:8080"
  env: "release" # should be debug, release, test

logger:
  isSave: false
  format: "console"
  level: "info"
  path: "./logs/log"

cache:
  enableCluster: false
  addressList: ["redis://127.0.0.1:6379"]
  password: ""
  db: 0
  prefix: ""

mysql:
  dsn: "root:123456@tcp(172.31.226.166:27890)/fido?charset=utf8&parseTime=True&loc=Local"
  maxIdleConns: 3
  maxOpenConns: 10
  slowThreshold: 0s
  connMaxLifetime: 30m
  enableLog: false

middleware:
  enableCircuitBreaker: false
  enableRateLimit: false
  enableMetrics: false
  enableTrace: false